### ISSUE TITLE
Title and album art are not fetched correctly

### ISSUE THREAD

**Issue by MarshallOfSound** [twolfson/google-music.js#14]
Google recently changed the ID's and classes on the album art and song title elements.  The change is indicated below  
`#player-song-title` became `#currently-playing-title`
`#playingAlbumArt` became `#playerBarArt`

The fix in my JS  
https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/commit/9705ef6e213ef924108ce75f8b39279db7cbda6c

**Comment by twolfson** [comment]
Awesome =) Would you be interested in opening a PR for that?

**Comment by MarshallOfSound** [comment]
Will be coming through in a few minutes, trying to get your test suite working :cactus:

**Comment by twolfson** [comment]
Yea, it's a finnicky one. If you have any ideas on how to improve it, I'm all ears (would love some CI).

Also, about to go AFK for a bit (maybe rest of the night) so if you don't hear from me, that's why ;)

**Comment by MarshallOfSound** [comment]
@twolfson Good news :smile: 
I fixed all the tests and have almost got the tests running on Travis CI, I'll link you when its working properly **#getexcited**

**Comment by MarshallOfSound** [comment]
And may I present, the first green build 
https://travis-ci.org/MarshallOfSound/google-music.js/builds/96546953

**Comment by twolfson** [comment]
Ah, sweet. Let's just hope the Selenium tests are bullet proof (I think 1 out of every 4 runs fails on my local machine =/)

**Comment by MarshallOfSound** [comment]
I'm at about 1 in 2 failing on mine.  When I up the timeouts I get less fails though so I'll be trying that tonight :D

**Comment by twolfson** [comment]
I think that's prob why I have avoided Selenium in CI for now ;)

**Comment by MarshallOfSound** [comment]
But the 1 in 2 appears to be related more to the test suite than selenium, it appears the test suite does not adaquetly reset itself after each run.  But running again will get a green build, I think it's due to the thumbs toggle tests toggling an odd number of times.

#lookingintoit

**Comment by twolfson** [comment]
In order for GitHub to auto-close, I think we need to say "Fixes #14" in the PR description:

https://help.github.com/articles/closing-issues-via-commit-messages/

This has been patched by @MarshallOfSound's work in #15 and released in `3.3.1`.

**Comment by twolfson** [comment]
We should prob move the Selenium discussion to another issue =/
