### ISSUE TITLE
Rename `toggleRepeat` to `setRepeat`

### ISSUE THREAD

**Issue by twolfson** [twolfson/google-music.js#26]
We currently allow `mode` as a parameter to `toggleShuffle`. A toggle probably shouldn't accept parameters, it should really only toggle. As a result, let's consider breaking it down into 2 methods:
- `setShuffle(mode)`
- `toggleShuffle()` which uses `getShuffle` and `setShuffle` under the hood

**Comment by MarshallOfSound** [comment]
I think what we mean here is
- `toggleShuffle()`
- `setShuffle(mode)` which uses `getShuffle` and `toggleShuffle` under the hood

Purely because `setShuffle` will simply `toggleShuffle` until `getShuffle` matches the required mode

**Comment by twolfson** [comment]
Ah, right. Nice catch =) Although, we can prob assume 2 clicks as opposed to inspecting the DOM after every toggle

**Comment by MarshallOfSound** [comment]
Note because I started looking at this, I think this is a breaking change?  Can you verify that @twolfson 

I.e. We would be removing functionality from `toggleShuffle`

**Comment by twolfson** [comment]
Nah, this should be backwards compatible. `toggleShuffle` doesn't accept any parameters so we should be fine as long as we keep it.

**Comment by twolfson** [comment]
That being said, we should prob rename `toggleRepeat` to `setRepeat` which would be a breaking change since we would strip the parameter from toggle

**Comment by twolfson** [comment]
But I guess I will file it as a separate issue

**Comment by twolfson** [comment]
Fun fact, this issue is actually a duplicate of #1 but I will correct this title to not be a "rename" and close the original one since this thread has more content

**Comment by twolfson** [comment]
Ohh, based on the thread I think I meant for this to be `setRepeat` since I mentioned `mode` =X

**Comment by MarshallOfSound** [comment]
I thought the whole point of this was `toggleShuffle` took parameters.  It's a bit late here so I'll check what I'm on about tomorrow :smile:

**Comment by twolfson** [comment]
Yea, it was typo on my part. We were originally talking about `toggleRepeat`:

https://github.com/gmusic-utils/gmusic.js/pull/19#discussion_r48099219

**Comment by twolfson** [comment]
If you are looking for `setShuffle`, then please see #1 instead =)
