### ISSUE TITLE
on('change:rating') not firing from outside changes

### ISSUE THREAD

**Issue by jacobwgillespie** [twolfson/google-music.js#33]
As best as I can tell, `on('change:rating')` isn't firing if the user manually changes the rating of a song.  

Code in use: https://github.com/radiant-player/radiant-player-mac/blob/gmusic-utils/radiant-player-mac/js/main.js.

**Comment by jacobwgillespie** [comment]
Did some digging and it looks like it's firing, but only when a thumbs up is applied, not when it's removed.

**Comment by twolfson** [comment]
Ah, nice catch. Yea, the problem is due to a `isElSelected` check:

**Comment by twolfson** [comment]
Ah, nice catch. Yea, the problem is due to a `isElSelected` check:

https://github.com/gmusic-utils/gmusic.js/blob/051eabf9c6a0410fe6b5c8e3cb4e61c9528417ed/lib/main.js#L475

We should be able to resolve it by saving the last rating via another variable and verifying it changed:

``` js
var lastRating;
var ratingObserver = new MutationObserver(function (mutations) {
  // Determine if our ratings were touched
  var ratingsTouched = mutations.some(function (m) {
    var target = m.target;
    return target.dataset && target.dataset.rating && target.hasAttribute('aria-label');
  });

  // If the ratings were touched and the rating changed, then fire an event
  if (ratingsTouched) {
    var newRating = that.rating.getRating();
    if (lastRating !== newRating) {
      lastRating = newRating;
      that.emit('change:rating', newRating);
    }
  }
});
```

**Comment by twolfson** [comment]
I think this solution/problem is prevalent in all observers (e.g. #29) so we should prob take care of all of them at the same time
