### ISSUE TITLE
`master` branch failing in Travis CI

### ISSUE THREAD

**Issue by twolfson** [twolfson/google-music.js#42]
When we released `5.0.0`, the `master` build for Travis CI broke. I have re-ran it twice but it keeps on timing out. Can someone take a look at this?

https://travis-ci.org/gmusic-utils/gmusic.js/builds/133861191

![selection_234](https://cloud.githubusercontent.com/assets/902488/15650700/1ec46154-2640-11e6-8bf3-7f43aacb7f27.png)

/cc @MarshallOfSound @jostrander

**Comment by jostrander** [comment]
I've got all tests passing on latest using browserstack, but I'm using my own account.

**Comment by twolfson** [comment]
Yea, the `5.0.0` tag built fine but not the `master` branch. I'm guessing something screwy is going on =/

**Comment by twolfson** [comment]
Going to run the `master` build again...

**Comment by twolfson** [comment]
Aaaand it passed. I guess there was something occupying the BrowserStack account or similar but I have no idea =(
