### ISSUE TITLE
Repository forking

### ISSUE THREAD

**Issue by twolfson** [twolfson/google-music.js#50]
In #47, we came to a realization that we have 2 sets of people with 2 incompatible architecture decisions. To prevent any future undesirable stress, we have decided to fork the repositories. This issue is to discuss the migration plan to make sure all parties are happy.

**Requests from `twolfson`:**
- I would like to relocate the `gmusic.js` repo back to my personal account (`twolfson`) so I can keep the stars and original history
- I will rename the repository back to `google-music` (until I get a cease and desist from Google)

**Plan outside of requests:**
- @jacobwgillespie, @MarshallOfSound, and @jostrander will be restored as Owners of `gmusic.js` in `npm`
- @MarshallOfSound and @jacobwgillespie will be promoted to Admins of `gmusic-utils`
- @twolfson will remove himself from the `gmusic-utils` organization

/cc @gmusic-utils/gmusic-js

**Comment by chrismou** [comment]
All sounds reasonable 👍

**Comment by jacobwgillespie** [comment]
Sounds reasonable to me as well 👍

**Comment by jostrander** [comment]
Agreed :+1:

**Comment by MarshallOfSound** [comment]
Sounds reasonable 👍

**Comment by twolfson** [comment]
Great, thanks for the approval everyone =) I'm not sure I will be able to get to this tonight but I will try to make time by the end of the weekend.

**Comment by twolfson** [comment]
Alright, checklist for self:
1. [x] Transfer repo to `twolfson`
2. [x] Rename repository to `google-music.js`
3. [x] Set up new admins on GitHub organization and `gmusic.js` team (albeit no repo)
4. [x] Add back `gmusic.js` owners on `npm`
5. [x] Perform renames again in repository (maybe we can do a revert for the majority of it; be sure to `git grep -i gmusic` and `ls` files)
6. [x] Remove Travis CI integration so @MarshallOfSound's BrowserStack account is freed back up
7. [x] Publish latest revision as a major release on `npm`
8. [x] Update `google-music-electron` to use `google-music` once again
9. [x] Close any lingering issues that would be better fitted for fork
10. [x] Remove self from GitHub organization
11. [x] Remove self from `gmusic.js` on `npm`
12. [x] Close this issue (since it's on @twolfson's repo)

**Comment by twolfson** [comment]
As a heads up, I encountered an issue locally with needing a password confirmation due to either not running the tests in a while or being in a country different from when I signed up (i.e. signed up in Chicago, now in Berlin). I resolved the issue here, it would probably be practical for your fork:

https://github.com/twolfson/google-music.js/compare/6.0.0...6.0.1

**Comment by twolfson** [comment]
Alright, transfer is complete. repo is renamed, and everyone is happy. Thanks again for all your work on this repository, it's been well appreciated =)

**Comment by jacobwgillespie** [comment]
Likewise, thank you as well!  👍
